### ISSUE TITLE
最新版本无法绑定公会，处理报错

### ISSUE THREAD

**Issue by shadow7755** [pcrbot/clanrank#12]
发送 绑定公会+UID 无法绑定工会，会报错
报错日志如下
[2020-12-28 03:35:59,361 公会战排名推送] ERROR: <class 'TypeError'> occured when set_clan handling message 783578050.
[2020-12-28 03:35:59,362 公会战排名推送] ERROR: argument of type 'int' is not iterable
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\hoshinobot\hoshino\msghandler.py", line 28, in handle_message
    await sf.func(bot, event)
  File "C:\Users\Administrator\Desktop\hoshinobot\hoshino\modules\clanrank\clanrank.py", line 259, in set_clan
    code = set_clanname(int(group_id),int(leader_id))
  File "C:\Users\Administrator\Desktop\hoshinobot\hoshino\modules\clanrank\clanrank.py", line 191, in set_clanname
    origin_info = get_rank(leader_id,"fav")
  File "C:\Users\Administrator\Desktop\hoshinobot\hoshino\modules\clanrank\clanrank.py", line 93, in get_rank
    if '[CQ:' in info and ']' in info and '=' in info:
TypeError: argument of type 'int' is not iterable

**Comment by var-mixer** [comment]
已修复（应该吧）
